version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: docker:20.10
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker Image
          command: |
            docker build . -t kytoonlabs/openwebsockets:latest
      - snyk/scan:
          docker-image-name: kytoonlabs/openwebsockets:latest
          severity-threshold: high
          fail-on-issues: true
          monitor-on-build: true
      - run:
          name: Login Docker Hub
          command: |
            echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
      - run:
          name: Push to Docker Hub
          command: |
            apk add --no-cache jq
            TAG=$(cat composer.json | jq -r '.version')
            docker tag kytoonlabs/openwebsockets:latest kytoonlabs/openwebsockets:$TAG
            docker push kytoonlabs/openwebsockets:$TAG
            docker push kytoonlabs/openwebsockets:latest
workflow:
  build-image:
    jobs:
      - build:
          filters:
              branches:
                only:
                  - main
